# Generated by Django 5.1.1 on 2024-11-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddrive', '0003_alter_restaurant_info_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
