# Generated by Django 5.1.1 on 2024-11-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrive', '0004_deliveryinfo_is_active_deliveryinfo_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='dasher',
        ),
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='dropoff_verification_pic',
        ),
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='pickup_phone_number',
        ),
    ]
